public class Kalkulator extends javax.swing.JFrame {
    String angka, historyAngka;
    double jumlah, bilangan1 = 0.0;
    double bilangan2 = 0.0;
    int pilih;
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(Kalkulator.class.getName());

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        angka = "";
        historyAngka = "";
        this.setLocationRelativeTo(null);
        this.setTitle("Kalkulator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private String formatHasil(double nilai) {
        if (nilai == (long) nilai) {
            return String.format("%d", (long) nilai);
        } else {
            return String.valueOf(nilai);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldHasilHistory = new javax.swing.JTextField();
        textFieldHasil = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonNomor0 = new javax.swing.JButton();
        buttonNomor1 = new javax.swing.JButton();
        buttonNomor2 = new javax.swing.JButton();
        buttonNomor3 = new javax.swing.JButton();
        buttonNomor4 = new javax.swing.JButton();
        buttonNomor5 = new javax.swing.JButton();
        buttonNomor6 = new javax.swing.JButton();
        buttonNomor7 = new javax.swing.JButton();
        buttonNomor8 = new javax.swing.JButton();
        buttonNomor9 = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonKoma = new javax.swing.JButton();
        buttonHasil = new javax.swing.JButton();
        buttonPenambahan = new javax.swing.JButton();
        buttonPengurangan = new javax.swing.JButton();
        buttonPerkalian = new javax.swing.JButton();
        buttonPembagian = new javax.swing.JButton();
        buttonPersen = new javax.swing.JButton();
        buttonMinusPositif = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 62, 103));
        jPanel1.setPreferredSize(new java.awt.Dimension(481, 750));

        textFieldHasilHistory.setEditable(false);
        textFieldHasilHistory.setBackground(new java.awt.Color(33, 62, 103));
        textFieldHasilHistory.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        textFieldHasilHistory.setForeground(new java.awt.Color(248, 248, 248));
        textFieldHasilHistory.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldHasilHistory.setBorder(null);
        textFieldHasilHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldHasilHistoryActionPerformed(evt);
            }
        });

        textFieldHasil.setBackground(new java.awt.Color(33, 62, 103));
        textFieldHasil.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        textFieldHasil.setForeground(new java.awt.Color(248, 248, 248));
        textFieldHasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFieldHasil.setBorder(null);
        textFieldHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldHasilActionPerformed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(480, 556));

        buttonNomor0.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor0.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor0.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor0.setText("0");
        buttonNomor0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor0ActionPerformed(evt);
            }
        });

        buttonNomor1.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor1.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor1.setText("1");
        buttonNomor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor1buttonNomor1ActionPerformed(evt);
            }
        });

        buttonNomor2.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor2.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor2.setText("2");
        buttonNomor2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor2ActionPerformed(evt);
            }
        });

        buttonNomor3.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor3.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor3.setText("3");
        buttonNomor3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor3ActionPerformed(evt);
            }
        });

        buttonNomor4.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor4.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor4.setText("4");
        buttonNomor4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor4buttonNomor4ActionPerformed(evt);
            }
        });

        buttonNomor5.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor5.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor5.setText("5");
        buttonNomor5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor5ActionPerformed(evt);
            }
        });

        buttonNomor6.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor6.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor6.setText("6");
        buttonNomor6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor6ActionPerformed(evt);
            }
        });

        buttonNomor7.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor7.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor7.setText("7");
        buttonNomor7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor7buttonNomor7ActionPerformed(evt);
            }
        });

        buttonNomor8.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor8.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor8.setText("8");
        buttonNomor8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor8ActionPerformed(evt);
            }
        });

        buttonNomor9.setBackground(new java.awt.Color(237, 237, 237));
        buttonNomor9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonNomor9.setForeground(new java.awt.Color(33, 62, 103));
        buttonNomor9.setText("9");
        buttonNomor9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonNomor9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNomor9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNomor9buttonNomor9ActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new java.awt.Color(237, 237, 237));
        buttonDelete.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(33, 62, 103));
        buttonDelete.setText("Del");
        buttonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletebuttonDeleteActionPerformed(evt);
            }
        });

        buttonKoma.setBackground(new java.awt.Color(237, 237, 237));
        buttonKoma.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonKoma.setForeground(new java.awt.Color(33, 62, 103));
        buttonKoma.setText(".");
        buttonKoma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonKoma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKomaActionPerformed(evt);
            }
        });

        buttonHasil.setBackground(new java.awt.Color(255, 214, 149));
        buttonHasil.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonHasil.setForeground(new java.awt.Color(33, 62, 103));
        buttonHasil.setText("=");
        buttonHasil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonHasil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHasiljButton29ActionPerformed(evt);
            }
        });

        buttonPenambahan.setBackground(new java.awt.Color(68, 93, 129));
        buttonPenambahan.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonPenambahan.setForeground(new java.awt.Color(237, 237, 237));
        buttonPenambahan.setText("+");
        buttonPenambahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPenambahan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPenambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPenambahanActionPerformed(evt);
            }
        });

        buttonPengurangan.setBackground(new java.awt.Color(68, 93, 129));
        buttonPengurangan.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonPengurangan.setForeground(new java.awt.Color(237, 237, 237));
        buttonPengurangan.setText("-");
        buttonPengurangan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPengurangan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPenguranganActionPerformed(evt);
            }
        });

        buttonPerkalian.setBackground(new java.awt.Color(68, 93, 129));
        buttonPerkalian.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonPerkalian.setForeground(new java.awt.Color(237, 237, 237));
        buttonPerkalian.setText("X");
        buttonPerkalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPerkalian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPerkalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerkalianjButton28ActionPerformed(evt);
            }
        });

        buttonPembagian.setBackground(new java.awt.Color(68, 93, 129));
        buttonPembagian.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonPembagian.setForeground(new java.awt.Color(237, 237, 237));
        buttonPembagian.setText("/");
        buttonPembagian.setToolTipText("");
        buttonPembagian.setAlignmentY(0.0F);
        buttonPembagian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPembagian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPembagian.setMargin(new java.awt.Insets(5, 14, 20, 14));
        buttonPembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPembagianbuttonPembagianActionPerformed(evt);
            }
        });

        buttonPersen.setBackground(new java.awt.Color(139, 163, 198));
        buttonPersen.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        buttonPersen.setForeground(new java.awt.Color(237, 237, 237));
        buttonPersen.setText("%");
        buttonPersen.setAlignmentY(0.0F);
        buttonPersen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPersen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersenbuttonPersenActionPerformed(evt);
            }
        });

        buttonMinusPositif.setBackground(new java.awt.Color(139, 163, 198));
        buttonMinusPositif.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonMinusPositif.setForeground(new java.awt.Color(237, 237, 237));
        buttonMinusPositif.setText("+/-");
        buttonMinusPositif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonMinusPositif.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonMinusPositif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinusPositifbuttonMinusPositifActionPerformed(evt);
            }
        });

        buttonReset.setBackground(new java.awt.Color(139, 163, 198));
        buttonReset.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        buttonReset.setForeground(new java.awt.Color(237, 237, 237));
        buttonReset.setText("AC");
        buttonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetbuttonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(buttonNomor7,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonNomor8,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonNomor9,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonPerkalian,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(buttonNomor1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonNomor2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonNomor3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonPenambahan,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(buttonNomor4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonNomor5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonNomor6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(17, 17, 17)
                                                                .addComponent(buttonPengurangan,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonNomor0, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17)
                                                .addComponent(buttonKoma, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17)
                                                .addComponent(buttonHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonMinusPositif,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(17, 17, 17)
                                                .addComponent(buttonPembagian, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(33, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonPembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonMinusPositif, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonReset, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonNomor7, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonNomor8, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonNomor9, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonPerkalian, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonNomor4, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonNomor5, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonNomor6, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonPengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonNomor1, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonNomor2, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonNomor3, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonPenambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(buttonNomor0,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonKoma,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonHasil,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textFieldHasilHistory, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 413,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addComponent(textFieldHasilHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void buttonResetbuttonResetActionPerformed(java.awt.event.ActionEvent evt) {
        bilangan1 = 0.0;
        bilangan2 = 0.0;
        jumlah = 0.0;
        angka = "";
        historyAngka = "";
        textFieldHasil.setText(angka);
        textFieldHasilHistory.setText(historyAngka);
    }

    private void buttonMinusPositifbuttonMinusPositifActionPerformed(java.awt.event.ActionEvent evt) {
        if (!angka.isEmpty() && !angka.equals("0")) {
            if (angka.startsWith("-")) {
                angka = angka.substring(1);

                if (historyAngka.endsWith(angka)) {
                    historyAngka = historyAngka.substring(0, historyAngka.length() - angka.length() - 1);
                    historyAngka += angka;
                }
            } else {
                String angkaLama = angka;
                angka = "-" + angka;

                if (historyAngka.endsWith(angkaLama)) {
                    historyAngka = historyAngka.substring(0, historyAngka.length() - angkaLama.length());
                    historyAngka += angka;
                }
            }

            textFieldHasil.setText(angka);
            textFieldHasilHistory.setText(historyAngka);
        }
    }

    private void buttonPersenbuttonPersenActionPerformed(java.awt.event.ActionEvent evt) {
        if (!angka.isEmpty()) {
            bilangan2 = Double.parseDouble(angka);
            historyAngka += "%";
            angka = "";
            pilih = 5; // persen
            textFieldHasil.setText("%");
            textFieldHasilHistory.setText(historyAngka);
        }
    }

    private void buttonPembagianbuttonPembagianActionPerformed(java.awt.event.ActionEvent evt) {
        if (!angka.isEmpty()) {
            bilangan1 = Double.parseDouble(angka);
        }
        if (bilangan1 != 0.0 || !angka.isEmpty()) {
            historyAngka += "/";
            angka = "";
            pilih = 4;
            textFieldHasil.setText("/");
            textFieldHasilHistory.setText(historyAngka);
        }
    }

    private void buttonPerkalianjButton28ActionPerformed(java.awt.event.ActionEvent evt) {
        if (!angka.isEmpty()) {
            bilangan1 = Double.parseDouble(angka);
        }
        if (bilangan1 != 0.0 || !angka.isEmpty()) {
            historyAngka += "x";
            angka = "";
            pilih = 3;
            textFieldHasil.setText("x");
            textFieldHasilHistory.setText(historyAngka);
        }
    }

    private void buttonPenguranganActionPerformed(java.awt.event.ActionEvent evt) {
        if (!angka.isEmpty()) {
            bilangan1 = Double.parseDouble(angka);
        }
        if (bilangan1 != 0.0 || !angka.isEmpty()) {
            historyAngka += "-";
            angka = "";
            pilih = 2;
            textFieldHasil.setText("-");
            textFieldHasilHistory.setText(historyAngka);
        }
    }

    private void buttonPenambahanActionPerformed(java.awt.event.ActionEvent evt) {
        if (!angka.isEmpty()) {
            bilangan1 = Double.parseDouble(angka);
        }
        if (bilangan1 != 0.0 || !angka.isEmpty()) {
            historyAngka += "+";
            angka = "";
            pilih = 1;
            textFieldHasil.setText("+");
            textFieldHasilHistory.setText(historyAngka);
        }
    }

    private void buttonKomaActionPerformed(java.awt.event.ActionEvent evt) {
        if (!angka.contains(".")) {
            if (angka.isEmpty()) {
                angka = "0.";
                historyAngka += "0.";
            } else {
                angka += ".";
                historyAngka += ".";
            }
            textFieldHasil.setText(angka);
            textFieldHasilHistory.setText(historyAngka);
        }
    }

    private void buttonDeletebuttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        if (!angka.isEmpty()) {
            angka = angka.substring(0, angka.length() - 1);
            textFieldHasil.setText(angka);
        }

        if (!historyAngka.isEmpty()) {
            historyAngka = historyAngka.substring(0, historyAngka.length() - 1);
            textFieldHasilHistory.setText(historyAngka);
        }
    }

    private void textFieldHasilActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void textFieldHasilHistoryActionPerformed(java.awt.event.ActionEvent evt) {
        textFieldHasilHistory.setText(historyAngka);
    }

    private void buttonHasiljButton29ActionPerformed(java.awt.event.ActionEvent evt) {
        switch (pilih) {
            case 1: // tambah
                bilangan2 = Double.parseDouble(angka);
                jumlah = bilangan1 + bilangan2;
                angka = formatHasil(jumlah);
                textFieldHasil.setText(angka);
                textFieldHasilHistory.setText(historyAngka);
                break;
            case 2: // kurang
                bilangan2 = Double.parseDouble(angka);
                jumlah = bilangan1 - bilangan2;
                angka = formatHasil(jumlah);
                textFieldHasil.setText(angka);
                textFieldHasilHistory.setText(historyAngka);
                break;
            case 3: // kali
                bilangan2 = Double.parseDouble(angka);
                jumlah = bilangan1 * bilangan2;
                angka = formatHasil(jumlah);
                textFieldHasil.setText(angka);
                textFieldHasilHistory.setText(historyAngka);
                break;
            case 4: // bagi
                bilangan2 = Double.parseDouble(angka);
                jumlah = bilangan1 / bilangan2;
                angka = formatHasil(jumlah);
                textFieldHasil.setText(angka);
                textFieldHasilHistory.setText(historyAngka);
                break;
            case 5: // persen
                if (bilangan1 != 0.0 & bilangan2 != 0.0) {
                    jumlah = ((bilangan1 * bilangan2) / 100);
                    angka = formatHasil(jumlah);
                    textFieldHasil.setText(angka);
                    textFieldHasilHistory.setText(historyAngka);
                } else {
                    jumlah = (bilangan2 / 100);
                    angka = formatHasil(jumlah);
                    textFieldHasil.setText(angka);
                    textFieldHasilHistory.setText(historyAngka);
                }
                break;
            default:
                break;
        }
    }

    private void buttonNomor9buttonNomor9ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "9";
        historyAngka += "9";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor8ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "8";
        historyAngka += "8";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor7buttonNomor7ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "7";
        historyAngka += "7";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor6ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "6";
        historyAngka += "6";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor5ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "5";
        historyAngka += "5";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor4buttonNomor4ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "4";
        historyAngka += "4";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor3ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "3";
        historyAngka += "3";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor2ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "2";
        historyAngka += "2";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor1buttonNomor1ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "1";
        historyAngka += "1";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    private void buttonNomor0ActionPerformed(java.awt.event.ActionEvent evt) {
        angka += "0";
        historyAngka += "0";
        textFieldHasilHistory.setText(historyAngka);
        textFieldHasil.setText(angka);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kalkulator().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonHasil;
    private javax.swing.JButton buttonKoma;
    private javax.swing.JButton buttonMinusPositif;
    private javax.swing.JButton buttonNomor0;
    private javax.swing.JButton buttonNomor1;
    private javax.swing.JButton buttonNomor2;
    private javax.swing.JButton buttonNomor3;
    private javax.swing.JButton buttonNomor4;
    private javax.swing.JButton buttonNomor5;
    private javax.swing.JButton buttonNomor6;
    private javax.swing.JButton buttonNomor7;
    private javax.swing.JButton buttonNomor8;
    private javax.swing.JButton buttonNomor9;
    private javax.swing.JButton buttonPembagian;
    private javax.swing.JButton buttonPenambahan;
    private javax.swing.JButton buttonPengurangan;
    private javax.swing.JButton buttonPerkalian;
    private javax.swing.JButton buttonPersen;
    private javax.swing.JButton buttonReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textFieldHasil;
    private javax.swing.JTextField textFieldHasilHistory;
    // End of variables declaration
}

